// <auto-generated />
using System;
using Control_Gasto_Publico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Control_Gasto_Publico.Migrations
{
    [DbContext(typeof(Control_Gasto_PublicoContext))]
    partial class Control_Gasto_PublicoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CG_P.Models.Agregar_Servicio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("fecha_servicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_edificio")
                        .HasColumnType("int");

                    b.Property<int>("id_servicio")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Agregar_Servicio");
                });

            modelBuilder.Entity("CG_P.Models.Edificio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("cantidad_personas")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_alquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_final_alquiler")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_canton")
                        .HasColumnType("int");

                    b.Property<int>("id_destrito")
                        .HasColumnType("int");

                    b.Property<int>("id_provincia")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_edificio")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Edificio");
                });

            modelBuilder.Entity("CG_P.Models.Servicio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre_empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("tipo_servicio_id")
                        .HasColumnType("int");

                    b.Property<int>("unidad_medida_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("CG_P.Models.Tipo_Servicio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Tipo_Servicio");
                });

            modelBuilder.Entity("CG_P.Models.Unidad_Medida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Unidad_Medida");
                });
#pragma warning restore 612, 618
        }
    }
}
